### ISSUE TITLE
Mapear expreso entre Estelí y León

### ISSUE THREAD

**Issue by AltNico** [mapanica/coordinacion#11]
Tengo el gpx del ruteado entre Estelí y León. Sería bonito si mapeamos eso.

**Comment by AltNico** [comment]
Hecho: [Estelí a León](https://www.openstreetmap.org/changeset/52464336)

Falta: León a Estelí

**Comment by pantierra** [comment]
Genial, @AltNico! Creo con las cooperativas y agencias del transporte interurbano también existirían posibilidades de colaboración. Incluso se podrían interesar en proveer servicios relacionados a éstos datos.

**Comment by ialokim** [comment]
Elaboré [una página en el OSM-Wiki](https://wiki.openstreetmap.org/wiki/ES:Wikiproyecto_Nicaragua) sobre las rutas expresos de Nicaragua; hasta ahora ya una y media está subida a OpenStreetMap, así que solamente nos faltan 49 y media! 🚀

**Comment by AltNico** [comment]
Acabo de mapear el bus de León a Estelí: https://osm.org/relation/7696091

Entonces, estamos listos con ese issue 👍
