### ISSUE TITLE
Mapear los urbanos de Esteli completamente conforme al estándar "Public transport v2"

### ISSUE THREAD

**Issue by ialokim** [mapanica/coordinacion#14]
Hasta ahora solo puse puntos del tipo `public_transport=stop_position` en los vías, aún faltan las plataformas (`public_transport=platform`). También use los mismos puntos de stop para las dos direcciones. Hay que revisar estas paradas y mapearlas mejor, también con la etiqueta `highway=bus_stop` para los mapas en linea.

**Comment by pantierra** [comment]
Todavía queda pendiente escribir un buen resumen (documentación) de manejar datos de transporte público con JOSM. Por el momento solo quedan unos pocos comentarios en el repositorio general de grote/osm2gtfs#12 Tal vez son de su utilidad.

Básicamente (tl;dr):

* Utilizar JOSM con extensión "pt_assistant", para validación de la los datos según `public_transport:version=2` y un diseño optimizado para datos de transporte público.
* Puede ser útil de activar "expert more" y descargar datos relacionados al transporte público con una consulta de overpass-api que hala únicamente datos conectados a relaciones con formato de  `public_transport:version=2`.

Tal vez juntos podemos elaborar un documento mejor en la [wiki de osm2gtfs](https://github.com/grote/osm2gtfs/wiki)

**Comment by ialokim** [comment]
He elaborado un estilo para JOSM para visualizar mejor las áreas de detención, puntos de detención y plataformas así que las rutas del transporte público.

Ver [Styles/PublicTransportV2](https://josm.openstreetmap.de/wiki/Styles/PublicTransportV2).

Aún faltan algunos tests.

**Comment by ialokim** [comment]
Todas las rutas están ya terminadas conforme al estándar.
