### ISSUE TITLE
Revisar Red Vial de Nicaragua

### ISSUE THREAD

**Issue by mikolaiguetschow** [mapanica/coordinacion#16]
Aquí se encuentra el informe anual del 2016 del Ministerio de Transporte e Infraestructura de Nicaragua sobre la red vial de Nicaragua. Se pueden comparar informaciones sobre el tipo de vía (troncal principal y secundaria, colectora principal y secundaria etc.) y la superficie (pavimentado, adoquinado etc.). Ver por ejemplo Página 168 y 169 para un mapa de toda Nicaragua.

- [Red Vial de Nicaragua 2016.pdf](http://biblioteca.mti.gob.ni:8080/docushare/dsweb/Get/DocumentosTecnicos-501/Red%20Vial%20de%20Nicaragua%202016.pdf)

**Comment by AltNico** [comment]
Voy a cerrar ese issue porque no sabemos si podemos usar el documento (licencia).
