### ISSUE TITLE
Revisar Áreas Protegidas de Nicaragua

### ISSUE THREAD

**Issue by mikolaiguetschow** [mapanica/coordinacion#17]
Aquí se encuentra el sistema completo de todas las áreas protegidas de Nicaragua.

- [sistema nacional de areas protegidas.jpg](http://www.marena.gob.ni/images/SIG/mapas%20a%20web/sistema%20nacional%20de%20areas%20protegidas.jpg)

**Comment by AltNico** [comment]
Voy a cerrar ese issue porque no sabemos si podemos usar el documento (licencia).
