### ISSUE TITLE
Paradas sin nombres en Estelí

### ISSUE THREAD

**Issue by AltNico** [mapanica/coordinacion#2]
Hay muchas paradas sin nombres en Estelí y sería mejor si tienen un nombre. Si no, no hay mucho problema porque `osm2gtfs` a veces encuentra un nombre automáticamente.

**Comment by AltNico** [comment]
Buen idea sería hacer el recorrido otra vez y pedir información a los ayudantes para encontrarlos.

**Comment by mikolaiguetschow** [comment]
Ver [Ayuda de OSM] (https://help.openstreetmap.org/answer_link/19204/):

> Of course one should not invent names for anything that has no name. If it has no name, then don't tag it with a name tag.

> 
If there are people announcing the stops like in Cusco, then they have names, even when they are not signposted.

Hay que hacer otros recorridos por la ciudad en las diferentes rutas y preguntar a los ayudantes por los nombres, si no se puede poner noname=yes (ver [Bus stops without name - OSM Help](https://help.openstreetmap.org/questions/35908/bus-stops-without-name))

**Comment by grote** [comment]
In Floripa, many stops also don't have names. Because of that, in `osm2gtfs` there's a feature where you can automatically take a name from an object in a 50m radius. If the stop is close to a church for example, it will get the name of that church. Note that this hammers the overpass API quite a bit though since a request is made for each nameless stop.

**Comment by AltNico** [comment]
@grote 
> Note that this hammers the overpass API quite a bit though since a request is made for each nameless stop.

But I already saw in the code that it is cached, so it's only hammered once 🙂 

Thanks for your comment, though. To translate the issues for you, @mikolaiguetschow and I are currently mapping everything related to public transport in Estelí and are then planning to create a creator for Estelí in osm2gtfs (https://github.com/mapanica/coordinacion/issues/6) while doing https://github.com/grote/osm2gtfs/issues/62 so that we can then later add creators for Managua (https://github.com/mapanica/coordinacion/issues/7) and national transport relatively easy.

**Comment by AltNico** [comment]
Fuimos a la alcaldía de Estelí y nos dijeron que no hay ninguna parada que tiene un nombre oficial. La pregunta ahora es: que hacemos? En mi opinión deberíamos mapear los nombres que los ayudantes dicen y también encontrar nuevos nombres de acuerdo a los puntos de referencia cercanos.

**Comment by ialokim** [comment]
Hice otro recorrido con el urbano 3 (Sandino-Hospital) y pregunte por los nombres. Los ayudantes si tienen nombres de las diferentes paradas y estaban muy dispuestos de compartirlos con nosotros.

Subí las paradas con los nombres correctos y conforme al estándar "Public Transport Scheme v2": [changeset](http://www.openstreetmap.org/changeset/52901066)

Ver también #14

**Comment by ialokim** [comment]
Ver #19. Terminado.
