### ISSUE TITLE
Crear creator en osm2gtfs para Estelí

### ISSUE THREAD

**Issue by AltNico** [mapanica/coordinacion#6]
Como con [Florianópolis](https://github.com/grote/osm2gtfs/tree/master/creators/fenix) e [Incofer](https://github.com/grote/osm2gtfs/tree/master/creators/incofer) necesitamos un `creator` en `osm2gtfs` para generar un `GTFS` del transporte público de Estelí. Interesante es el `creator` de [Accra](https://github.com/grote/osm2gtfs/pull/66).

**Comment by AltNico** [comment]
Mira el [issue sobre un formato estándar de horarios en `osm2gtfs`](https://github.com/grote/osm2gtfs/issues/62) con un [ejemplo](https://github.com/Skippern/GV-scraper/blob/498d1cd/creators/lorenzutti/times.json).

**Comment by xirapo** [comment]
Yo hice un fork , esta un poco outdated pero logre generar el gtf para la ruta 105 de managua, por cuestion de tiempo no he podido seguir pero la ayuda siempre es bien recibida [Fork de Osm2Gtfs](https://github.com/xirapo/osm2gtfs/tree/working_on_tripsl).

**Comment by AltNico** [comment]
Estamos caminando con pasos grandes a ese objetivo: https://github.com/grote/osm2gtfs/pull/70, https://github.com/grote/osm2gtfs/pull/72, https://github.com/grote/osm2gtfs/pull/73. Cuando todos esos están listos, puedo abrir un pull request con [ese configuración](https://github.com/AltNico/osm2gtfs/tree/creator-esteli/creators/esteli) y [ese horario](https://github.com/mapanica/coordinacion/issues/3#issuecomment-333997433) con facilidad:
```
{
    "query": {
        "bbox": {
            "n": "13.1308234",
            "s": "13.0534171",
            "e": "-86.3197351",
            "w": "-86.3999775"
        },
        "tags": {
            "route": "bus"
        }
    },
    "stops": {
        "name_without": "Parada sin nombre",
        "name_auto": "yes"
    },
    "agency": {
        "agency_id": "NI-Estelí",
        "agency_name": "Estelí",
        "agency_url": "https://en.wikipedia.org/wiki/Estel%C3%AD",
        "agency_timezone": "America/Managua",
        "agency_lang": "ES",
        "agency_phone": "",
        "agency_fare_url": ""
    },
    "feed_info": {
        "publisher_name": "Nico Alt",
        "publisher_url": "https://nico.dorfbrunnen.eu",
        "version":  "0.1"
    },
    "output_file": "data/ni-esteli.zip",
    "selector": "esteli"
}
```

**Comment by ialokim** [comment]
El strandard creator que se usa para Estelí está en proceso de merging. Ver [osm2gtfs](https://github.com/grote/osm2gtfs/pull/99) para información actualizada.
