### ISSUE TITLE
Crear creator en osm2gtfs para Managua

### ISSUE THREAD

**Issue by AltNico** [mapanica/coordinacion#7]
Similar como con Estelí (#6), Managua necesita un `creator` en `osm2gtfs` para generar un `GTFS` del transporte público de Estelí. Interesantes son los `creator`s de [Accra](https://github.com/grote/osm2gtfs/pull/66), [Florianópolis](https://github.com/grote/osm2gtfs/tree/master/creators/fenix) e [Incofer](https://github.com/grote/osm2gtfs/tree/master/creators/incofer). Mira el [issue sobre un formato estándar de horarios en `osm2gtfs`](https://github.com/grote/osm2gtfs/issues/62) con un [ejemplo](https://github.com/Skippern/GV-scraper/blob/498d1cd/creators/lorenzutti/times.json).

@xirapo escribió:
> Yo hice un fork, esta un poco outdated pero logre generar el gtf para la ruta 105 de managua, por cuestión de tiempo no he podido seguir pero la ayuda siempre es bien recibida [Fork de Osm2Gtfs](https://github.com/xirapo/osm2gtfs/tree/working_on_trips).

**Comment by AltNico** [comment]
@xamanu @xirapo: En la reunión en Julio había un horario con todos los tiempos de las paradas en Managua, pero ahora no puedo encontrarlo. ¿Podría alguien de ustedes subirlo aquí en GitHub o dejar el link a ese documento? ¡Muchas gracias!

**Comment by sizco29** [comment]
Ahorita he estado checkiando lo nuevo que se ha estado cambiando en el OSM2GTFS de grote y voy a adaptar el creator de managua , hablare con james de costarica que es el que esta haciendo incofer para ponerme al tanto de las cosas que se estan llevando acabo no he podido hacer nada por cuestion de trabajo , pero ya afinales de octubre tendre tiempo. ese horario lo tiene porfirio @porfiriopaiz  o @mayorgatellez

**Comment by AltNico** [comment]
@xirapo: Gracias por tu repuesta. Pregunté porque [trabajo en osm2gtfs](https://github.com/mapanica/coordinacion/issues/6#issuecomment-335674011) con el objetivo de poner las ciudades de Estelí y Managua y algunas rutas nacionales de Nicaragua en Transportr. Por eso sería bueno que conozca el formato de Managua porque la próxima tarea es el [default trip creator](https://github.com/grote/osm2gtfs/pull/73).

**Comment by sizco29** [comment]
Managua ya casi esta lista si fijas en el branch [Working_on_trips](https://github.com/xirapo/osm2gtfs/tree/working_on_tripsl) que hice y lo descargas el gtfs se genera pero solo para la ruta 105 , hay que arreglar unas cosas que quedaron pendientes y actualizarlo a los cambios recientes que se estan haciendo.

**Comment by pantierra** [comment]
Hoy empezamos a convertir el CSV de las frequencias al formato estándar json (grote/osm2gtfs#62). Con éste supongo que podemos implementar un default trip creator (grote/osm2gtfs#73) en vez de uno particular para Managua.

Rápidamente eché un ojo a tu branch de `working_on_trips`, @xirapo, y no me queda claro porque necesitamos sobreescribir los default creators para stops y routes. A mi parecer Managua, podría ser la primera ciudad que se implementará completamente basados en "defaults" :joy:

**Comment by sizco29** [comment]
@xamanu lo que pasa que estaba trabajando con james en los grouping stops pero con los cambios que se han hecho al git original creo que ya no se necesita y si podriamos usar los defaults. disculpa por no estar trabajando en proyecto pero he tenido unos meses bien pesados. a finales de octubre ya tendre tiempo y puedo trabajar si todavia se necesita ayuda. me alegra que se este trabajando el de esteli.

**Comment by pantierra** [comment]
Qué te parece éso @xirapo: [output.json](https://raw.githubusercontent.com/xamanu/timetable-csv2json/master/data/output.json)

Inicialmente pensaba integrar la lógica en osm2gtfs, pero ahora con el formato casi estándar preferí de meter ése código (bastante espagueti) en un [script aparte](https://github.com/xamanu/timetable-csv2json)

Sí lo entiendo bien, éso fue la parte que hacía falta. A lo mejor ahora se puede combinar el trabajo de todos y tendrémos un GTFS!?

**Comment by ialokim** [comment]
El strandard creator que se usa para Managua está en proceso de merging. Ver [osm2gtfs](https://github.com/grote/osm2gtfs/pull/99) para información actualizada.
