### ISSUE TITLE
Contactar horariodebuses.com

### ISSUE THREAD

**Issue by AltNico** [mapanica/coordinacion#9]
Para preguntar el formato de los horarios (base de datos u otro) y la disponibilidad para compartir los datos con nosotros.

Nota: En [este sitio web](http://horariodebuses.com/) se encuentran horarios de buses, trenes y barcos de gran parte de Latinoamérica.

**Comment by AltNico** [comment]
> Hello!
> 
> I am Mikolai Gütschow and I'm currently working voluntarily on making schedules of public transport in Nicaragua more accessible. Therefore I found your website some time ago and it already helped me a lot. Thank you for your work!
> 
> However, there are some initiatives around OpenStreetMap and free software bringing schedules to mobile devices. One example is Transportr, an app for Android, which is fully free and open source and continuously developed by a community and filled with data. For more information, see their website at https://transportr.grobox.de/
> 
> As you already have a lot of data about public transport in Latin America, I'm wondering whether you would like to make your data publicly accessible for others to use them for projects like the mentioned, too.
> 
> Thanks a lot
> 
> Mikolai Gütschow

**Comment by AltNico** [comment]
@mikolaiguetschow ¿Ya recibiste una repuesta? Si no, pienso que podemos cerrar ese issue.

**Comment by ialokim** [comment]
Lastimosamente no, y tampoco ya no espero recibir una 🙈
